#! /usr/bin/env bash
#set -x


# always create a log file for 
:> logfile

# create special stdout/stderr (which always receive encoded output)
exec 3>&1

#exec 4>&2

( {
echo sew 2>&1
echo 'hello'
  } 2>&1  | tee /dev/fd/3 | sed -E 's|e|a|g' >> logfile)

# close special stdout/stderr
#exec 4>&-
exec 3>&-

while read -r line;do
    echo $line
done < logfile
