#!/bin/bash -v

#alpine/build_container

cd ~/GIT/support

declare  -a images=( alpine/cesi/2.4
alpine/cesi/2.5.0
alpine/cesi/2.6.0
alpine/cesi/2.6.2
alpine/cesi/2.6.3
alpine/cesi/2.6.6
alpine/files-kafka
alpine/files-librd
alpine/gradle/4.10.2
alpine/gradle/4.9
alpine/jenkins/2.138.1
alpine/jenkins/2.138.2
alpine/jenkins/2.138.3
alpine/jenkins/2.150.1
alpine/jenkins/2.150.2
alpine/jenkins/2.150.3
alpine/kafka-broker/2.0.0
alpine/kafka-broker/2.0.1
alpine/kafka-broker/2.1.0
alpine/kafka-manager/1.3.3.18
alpine/kafka-manager/1.3.3.22
alpine/kafka-manager/1.3.3.23
alpine/kafka-rest/5.1.0
alpine/kafka-zookeeper/3.4.13
alpine/kafka/2.1.0
alpine/kafka/2.1.1
alpine/openjdk/8.0.201.b09
alpine/openjdk/8.171.11-r0
alpine/openjdk/8.181.13-r0
alpine/openjdk/8.191.12-r0
alpine/openjre/8.171.11-r0
alpine/openjre/8.181.13-r0
alpine/openjre/8.191.12-r0
alpine/phpmyadmin/4.8.3
alpine/postgresql/10.5
alpine/postgresql/10.6
alpine/postgresql/11.1
i386-ubuntu/kafka-broker/1.1.0
i386-ubuntu/kafka-broker/2.0.0
i386-ubuntu/kafka-broker/2.0.1
i386-ubuntu/kafka-broker/2.1.0
i386-ubuntu/kafka-zookeeper/3.4.10
i386-ubuntu/kafka-zookeeper/3.4.13
i386-ubuntu/kafka/2.1.0
ubuntu
ubuntu/base_container
ubuntu/openjdk/1.8.0_181
)
./deleteImages "${images[@]}"

