#!/bin/bash

#----------------------------------------------------------------------------
# calculate the elapsed time for an event
function timer.fmtElapsed()
{
    local -ir elapsed=${1:?"Input parameter 'elapsed' must be passed to 'function ${FUNCNAME[0]}()'"}

    printf '%02d:%02d:%02d' $((elapsed / 3600)) $((elapsed % 3600 / 60)) $((elapsed % 60))
}
export -f timer.fmtElapsed

#----------------------------------------------------------------------------
# log elapse time result
function timer.logElapsed()
{
    local -r name=${1:?"Input parameter 'name' must be passed to 'function ${FUNCNAME[0]}()'"}
    local -ir elapsed=${2:?"Input parameter 'elapsed' must be passed to 'function ${FUNCNAME[0]}()'"}

    printf 'Time elapsed (%s): %s' "$name" "$(timer.fmtElapsed $elapsed)"
}
export -f timer.logElapsed

#----------------------------------------------------------------------------
# get the timestamp of a file in seconds
function timer.getTimestamp()
{
    date +%s
}
export -f timer.getTimestamp

#---------------------------------------------------------------------------- 

declare -i count i t1 t2 t3

count=${1:-1000}
t1=$(timer.getTimestamp)
for (( i=0; i<$count; i++ )); do
    echo -n ',' >/dev/null
done
t2=$(timer.getTimestamp)
for (( i=0; i<$count; i++ )); do
    printf ',' >/dev/null
done
t3=$(timer.getTimestamp)

timer.logElapsed 'echo  ' $(( t2 - t1 ))
echo
timer.logElapsed 'printf' $(( t3 - t2 ))
echo
