#!/usr/bin/bash

# run command on all systems

declare asroot=''
if [ "$#" -eq 0 ]; then
    echo 'this script will execute a command on all systems'
elif [ "$1" = 'asroot' ]; then
   asroot="$(dirname "$(readlink -f "$0")")/asroot"
   shift
fi


declare cmd
if [ "$#" -eq 0 ]; then
    echo 'this script will execute a command on all systems'
elif [ -e "${HOME}/.bin/$1" ]; then
    cmd="$(printf '%s/.bin/%s' "$HOME" "$1")"
    shift
elif [ -e "${HOME}/.bin/test/$1" ]; then
    cmd="$(printf '%s/.bin/test/%s' "$HOME" "$1")"
    shift
else
    cmd="$(printf '%s' "$1")"
    shift
fi

# iterate over all systems
for h in pi s{1..8};do
    printf '\n\e[95m%s:\e[0m\n' "$h.ubuntu.home"
    ssh -tt "bobb@$h.ubuntu.home" "$asroot" "$cmd" "$@" < /dev/tty
done
echo
