#!/bin/bash
#############################################################################
#
#   bashlib.sh
#
#############################################################################

function createUserAndGroup()
{
    local -r user=$1
    local -r uid=$2
    local -r group=$3
    local -r gid=$4
    local -r homedir=$5
    local -r shell=$6 

    /usr/sbin/groupadd --gid "${gid}" "${group}"
    if [ "$homedir" = '--no-create-home' ]; then
        /usr/sbin/useradd  --no-create-home --uid "${uid}" --gid "${gid}" --shell "${shell}" "${user}" 
    else
        /usr/sbin/useradd --home-dir "$homedir" --uid "${uid}" --gid "${gid}" --shell "${shell}" "${user}" 
    fi
}

#############################################################################
function perlmodver
{
  perl -M$1 -e 'print "Version ".$ARGV[0]->VERSION." of ".$ARGV[0]." is installed.\n";' $1
}

#############################################################################
function rmOldContainers()
{
    local -a collection

    # remove all containers which are stopped along with their associated volumes
    collection=()
    collection=( $(docker ps --all --quiet --filter "status=exited" --filter "status=dead" --format "{{.Names}}") )
    if [ ${#collection[@]} -gt 0 ]; then
        printf "Deleting %d exited containers\n" ${#collection[@]}
        docker rm --volumes "${collection[@]}"
    fi

    # remove any 'dangling' images  (those with <none> in name)
    collection=( $(docker images --quiet --filter "dangling=true") )
    if [ ${#collection[@]} -gt 0 ]; then
        printf "Deleting %d dangling images\n" ${#collection[@]}
        docker rmi "${collection[@]}"
    fi

    # get list of volumes associated with running containers
    collection=()
    for volume in $(docker ps --all --quiet); do
        collection+=( $(docker inspect "$volume" | jq -r '.[] | .Mounts | .[] | .Name | select(.)') )
    done
    printf "Detected %d mounts associated with running containers\n" ${#collection[@]}
    local volumes="$( printf "%s\n" "${collection[@]}" )"

    # remove directories associated with unused volumes
    collection=()
    for dir in $(sudo find '/var/lib/docker/volumes/' -mindepth 1 -maxdepth 1 -type d); do
        (grep "$dir" <<< "$volumes") && continue
        collection+=( "$dir" )
    done
    if [ ${#collection[@]} -gt 0 ]; then
        printf "Deleting %d directories associated with volumes no longer in use\n" ${#collection[@]}
        sudo rm -rf "${collection[@]}"
    fi

    docker images
}

#############################################################################
function findInProjects()
{
    cd /home/bobb
    for f in $(sudo find support prod -maxdepth 4 -type d -name 'build' | sort); do
        grep -rE "$1" "$f"
    done
}

#############################################################################
function dockerImages()
{
   docker images
}

#############################################################################
function dockerProcesses()
{
   docker ps --format "table {{.Names}}\t{{.ID}}\t{{.Size}}\t{{.Status}}\t{{.RunningFor}}\t{{.Ports}}"
}

#############################################################################
function dockerNetworks()
{
   docker network inspect $( docker network ls | grep 'default' | awk "{ print \$1 }") | jq ".[].Containers|.[]|[.IPv4Address + \" : \" + .Name]|.[]" | sort -t "." -k 4g
}

#############################################################################
function removeCurrentContainers()
{
    local -a containers=( $(docker images -q -f "reference=*:2018*"  --format "{{.Repository}}:{{.Tag}}") )
    [ ${#containers[@]} -eq 0 ] || docker rmi --force "${containers[@]}"
    docker images
}
