#!/bin/bash

# do nothing when we are not in a GIT directory
if [ $(git rev-parse --is-inside-work-tree) != 'true' ]; then
    echo -e "    \e[93m$(pwd) is not a GIT directory\e[0m"
    exit 0
fi

declare master="${1:-master}"

declare -i count=0
while read -r test_branch; do

    [ "$test_branch" != "$master" ] && continue
    (( count++ )) ||:

done < <(git for-each-ref --format="%(refname:lstrip=2)" refs/heads)


# do nothing when $master does not exist
if [ $count -eq 0 ]; then
    echo -e "    \e[93m${master} branch does not exist\e[0m"
    exit 0
fi

while read -r test_branch; do

    [ "$test_branch" = "$master" ] && continue
    declare distance=$(git rev-list --left-right --count ${master}...${test_branch} | awk '{print $2}')
    [ "$distance" -eq 0 ] && continue
    echo "    $test_branch:  $distance commits from $master"

done < <(git for-each-ref --format="%(refname:lstrip=2)" refs/heads)
