#!/bin/bash

#---------------------------------------------------------------------------------------------- 
function gitReferenceBranch()
{
    local ref="$(git config --get core.branch)"
    [ -z "$ref" ] && ref='main'
    echo $ref
}

#---------------------------------------------------------------------------------------------- 

# do nothing when we are not in a GIT directory
declare insideWorkTree="$(git rev-parse --is-inside-work-tree 2>/dev/null)"
if [[ $? != 0 || "$insideWorkTree" != 'true' ]]; then
    echo -e "\e[93m$(pwd) is not a GIT directory\e[0m"
    exit 0
fi

declare repo="$(basename "$(git remote get-url origin)")"
repo="${repo/.git}"

declare ref="${1:-$(gitReferenceBranch)}"
[ $(git rev-parse --verify --quiet "origin/$ref" &> /dev/null ; echo $?) -eq 0 ] || exit 0
 

declare -i count=0
while read -r test_branch; do

    [ "$test_branch" != "$ref" ] && continue
    (( count++ )) ||:

done < <(git for-each-ref --format="%(refname:lstrip=2)" refs/heads)


# do nothing when $ref does not exist
if [ $count -eq 0 ]; then
    echo -e "    \e[93m${main} branch does not exist\e[0m"
    exit 0
fi

declare -i LEFT_AHEAD RIGHT_AHEAD

while read -r test_branch; do

    [ "$test_branch" = "$ref" ] && continue

    git rev-list --left-right ${test_branch}...origin/${main} -- 2>/dev/null >/tmp/git_upstream_status_delta || continue
    LEFT_AHEAD=$(grep -c '^<' /tmp/git_upstream_status_delta)
    RIGHT_AHEAD=$(grep -c '^>' /tmp/git_upstream_status_delta)
    [ $LEFT_AHEAD -eq 0 ] && [ $RIGHT_AHEAD -eq 0 ] && continue
    echo "${repo} | ${test_branch} (ahead $LEFT_AHEAD) | (behind $RIGHT_AHEAD) origin/$ref"

#    declare distance=$(git rev-list --left-right --count origin/${main}...${test_branch} | awk '{print $2}')
#    [ "$distance" -eq 0 ] && continue
#    echo "${repo} ${test_branch}:  ${distance} commits from $ref"

done < <(git for-each-ref --format="%(refname:lstrip=2)" refs/heads)
