#!/bin/bash

declare -a containers
#set -o xtrace

containers=( $(docker ps -q) )
[[ "${containers[@]}" ]] && docker stop ${containers[@]}
containers=( $(docker ps -aq --filter "status=running" --filter "status=restarting" --filter "status=paused") )
[[ "${containers[@]}" ]] && docker kill ${containers[@]}
containers=( $(docker ps -aq) }
[[ "${containers[@]}" ]] && docker rm -f ${containers[@]}
containers=( $(docker images -aq) )
[[ "${containers[@]}" ]] && docker rmi -f ${containers[@]}
