#!/bin/bash

declare -a containers
#set -o xtrace

containers="$(docker ps -q)"
[[ "${containers[@]}" ]] && docker kill ${containers[@]}
containers="$(docker images -a -q)"
[[ "${containers[@]}" ]] && docker rmi -f ${containers[@]}
containers="$(docker images -a --filter=dangling=true -q)"
[[ "${containers[@]}" ]] && docker rmi -f ${containers[@]}
containers="$(docker ps --filter=status=exited --filter=status=created -q)"
[[ "${containers[@]}" ]] && docker rm -f ${containers[@]}
containers="$(docker images -a -q)"
[[ "${containers[@]}" ]] && docker rmi -f ${containers[@]}
