#!/bin/bash
#############################################################################
#
#   dockerComposeServices
#
#############################################################################

declare yaml=${1:-docker-compose.yml}
if [ ! -e "$yaml" ]; then
    echo "Unable to locate $yaml"
    exit 1
fi

declare jsonConfig=$(python -c 'import sys, yaml, json; json.dump(yaml.load(sys.stdin), sys.stdout, indent=4)' < "$yaml" | jq -c '.services?')
if [ -z "${jsonConfig:-}" ]; then
    echo "Invalid file: $yaml"
    exit 1
fi

jq -r 'keys[]?' <<< "$jsonConfig"
