#!/bin/bash
#############################################################################
#
#   dockerNetworks
#
#############################################################################

IFS=$'\n\t'
declare -a networks=( $( docker network ls | grep 'default' | awk "{ print \$1 }" ) )
docker network inspect "${networks[@]}" | \
    jq -r ".[].Containers|.[]|[.IPv4Address + \" : \" + .Name]|.[]" | \
    sort -t "." -k 4g
