#!/bin/bash

{
  for line in $(mount | grep 'overlay'); do
    echo $line \
     | awk '{print $0}' RS=':' \
     | awk '{print $0}' RS=',' \
     | awk '{print $0}' RS='=' \
     | grep -vE 'snapshots|^$' \
     | grep '/' \
     | sed -e 's|)||' \
     | sed -E -e 's:/(diff|merged|work)::'
  done
} | sort -u -s | sed -E 's|^.+/(.+/.+)$|\1|' | sed -e 's|/rootfs||' -e 's|^.*/||' | grep -vE 'sda|overlay'
