#!/bin/bash

function gitMainBranch()
{
    local master="$(git config --get core.branch)"
    [ -z "$master" ] && master='master'
    echo $master
}

declare -r MASTER=$(gitMainBranch)

git checkout $MASTER
git keep

git checkout dev
git reset --hard $MASTER
git push -f

git checkout --detach origin/$MASTER
git br -D $MASTER
git br -D dev
git log --graph --abbrev-commit --decorate --all -n 16 \
        --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)'
