#!/bin/bash

# do nothing when we are not in a GIT directory
if [ $(git rev-parse --is-inside-work-tree) != 'true' ]; then
    echo 'this is not a GIT directory'
    exit 0
fi

git for-each-ref --format='%(refname)' | while read ref; do git lfs ls-files "$ref"; done | sort -u
