#!/bin/bash

#------------------------------------------------------------------------------
function module_map() {
  local -i i=0
  local line line2 repo
  while read -r line; do
    case "$i" in
      0) i=1
         ;;
      1) line2="${line#*= }"
         i=2
         ;; 
      2) repo="${line#*= ../}"
         repo="${repo%.git*}"
         echo -e "['"${repo}"']='"${line2}"'"
         i=0
         ;;
    esac
  done < .gitmodules
}

#------------------------------------------------------------------------------
function modified_modules() {
  local module dir
  for module in $(git submodule foreach branch-distance | grep '(behind 0)' | cut -d ' ' -f 1); do
    dir="${module_paths[$module]}"
    pushd "$dir" >/dev/null
    printf '%-27s %27s :  %s\n' "${dir}/" "($module)" "$(git log -1 --format=%s)"
#    HUB_VERBOSE=1 hub pull-request --file "$prfile" -r svc_cyclonebuild  1>pr.stdout 2>pr.stderr
#    hub pr list
    popd >/dev/null
  done
}

#------------------------------------------------------------------------------

export GITHUB_HOST=eos2git.cec.lab.emc.com
export HUB_PROTOCOL=https
#export HUB_VERBOSE=1
export GITHUB_USER=ballab1 

declare -A module_paths
eval "module_paths=( $(module_map) )"

declare prfile=/tmp/pr
cat << EOF > "$prfile"
[DevOps-F4072] cbf improvements

 - add more utility scripts
 - move all thirdparty images to own location in registry
 - hardening of build.sh, deploy and docker-utilities
 - updated versions of Jenkins, Grafana, nginx, phpmyadmin, pgAdmin4
EOF

echo '-- PR comment --------------------------------------------------'
cat "$prfile"
echo '----------------------------------------------------------------'

modified_modules

echo '----------------------------------------------------------------'

rm "$prfile"
