#!/bin/bash

function module_map() {
  local -i i=0
  local line line2 repo
  while read -r line; do
    case "$i" in
      0) i=1
         ;;
      1) line2="${line#*= }"
         i=2
         ;; 
      2) repo="${line#*= ../}"
         repo="${repo%.git*}"
         echo -e "['"${repo}"']='"${line2}"'"
         i=0
         ;;
    esac
  done < <(cat .gitmodules)
}

declare -A module_paths
eval "module_paths=( $(module_map) )"

declare sm d
for sm in $(git submodule foreach branch-distance | grep '(behind 0)' | cut -d ' ' -f 1); do
  d=${module_paths[$sm]}
  pushd $d >/dev/null;
  echo "$sm:  $d : $(git log -1 --format=%s)"
  popd >/dev/null
done


