#!/bin/bash -v

cd ~/prod
docker-compose -f ~/prod/dc.yml down

sudo find -L vols/log -type f ! -name '.*' -delete

cd ~/prod
docker-compose -f ~/prod/dc.yml up -d

sudo find -L vols/log -type f ! -name '.*' -exec chmod 666 '{}' \;
