#!/usr/bin/bash


DOCKER_COMPOSE_VER=2.23.3
declare re='^\d+\.\d+\.\d+$'

 # if provided with 'all' parameter
if [ "$#" -gt 0 ]; then
   if [[ "$1" =~ $re ]]; then
     DOCKER_COMPOSE_VER="$1"

   elif [ "$1" = 'all' ]; then
     declare cmd="$(readlink -f $(which "$0"))"
     for h in pi s{1..8};do
       echo "$h.ubuntu.home"
#       ssh "$h.ubuntu.home" "$cmd"
       ssh "$h.ubuntu.home" '/home/bobb/.bin/upgradeDockerCompose'
     done
     exit
   fi
fi

# do not run on pi or s2
[ "$(uname -m)" = 'x86_64' ] || exit

# ensure this script is run as root
if [[ $EUID != 0 ]]; then
  sudo --preserve-env "$0" "$@"
  exit
fi

# perform update
declare download="/usr/local/bin/docker-compose.${DOCKER_COMPOSE_VER}"

curl --silent --location https://github.com/docker/compose/releases/download/v${DOCKER_COMPOSE_VER}/docker-compose-$(uname -s)-$(uname -m) -o "$download"
[ "$?" -eq 0 ] || exit 1
[ "$(stat -c %s "$download")" -gt 100 ] || exit 1

chmod 755 "$download"
rm /usr/bin/docker-compose
ln -s "$download" /usr/bin/docker-compose
