#!/bin/bash

[ "$(uname -m)" = 'x86_64' ] || exit

# ensure this script is run as root
if [[ $EUID != 0 ]]; then
  sudo --preserve-env $0
  exit
fi

declare version=2.11.0
declare download="/usr/local/bin/docker-compose.${version}"

curl --silent --location https://github.com/docker/compose/releases/download/v${version}/docker-compose-$(uname -s)-$(uname -m) -o "$download"
[ "$?" -eq 0 ] || exit 1
[ "$(stat -c %s "$download")" -gt 100 ] || exit 1

chmod 755 "$download"
rm /usr/bin/docker-compose
ln -s "$download" /usr/bin/docker-compose
