alias cbr='cbfRepos'
alias dbc='debugContainer'
alias dbs='debugBashScript'
alias dc='docker-compose_deploy-extension'
alias de='docker-exec_extension'
alias dive='docker run -ti --rm -v /var/run/docker.sock:/var/run/docker.sock s2.ubuntu.home:5000/docker.io/wagoodman/dive:v0.12'
alias dl='docker logs'
alias dr='docker run -it --rm --entrypoint bash'
alias drm='docker rmi'
alias ds='docker-search.py'
alias dt='docker top'

alias dcs='docker-utilities show --services'
alias dim='docker-utilities show --images'
alias dnt='docker-utilities show --networks'
alias dps='docker-utilities show --processes'
alias roc='docker-utilities clean'
alias getImage='docker-utilities getImage'
#alias kafkacat='/usr/bin/kafkacat -b "$KAFKA_BOOTSTRAP_SERVERS"'

alias dut='docker-utilities'

alias gk='git-keep'
alias gl='git lg'
alias gr='git-revision'
alias gs='git status-extended'


alias env='/usr/bin/env | sort'
#alias rcc='docker-utilities remoteLocal'


alias rlg='dockerRunLogs'
alias tmux='/usr/bin/tmux -f ~/.tmux/tmux.conf'
[ "$(which kubectl)" ] || alias kubectl='/snap/bin/kubectl'
alias kc="$(which kubectl|sed 's: :\\ :g')"
