#!/bin/bash

declare -r PERFORM_UPDATE=${1:-'false'}
declare -r JOBS_DEFINITION_FILE
declare -r XML_PATH='//userRemoteConfigs/hudson.plugins.git.UserRemoteConfig/url'
declare -r GIT_ARG='/emc/ballab1/Downloads/jenkins/UserRemoteConfig.xml'
declare -r ACCUREV_ARG='/emc/ballab1/Downloads/jenkins/UserRemoteConfig.xml'

# locate main script
declare -r UPDATE_JOBS="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. "${UPDATE_JOBS}/update_jobs"