#!/bin/bash

declare -r PERFORM_UPDATE=${1:-'false'}
declare -r JOBS_DEFINITION_FILE
declare -r XML_PATH='//parameterDefinitions/hudson.model.StringParameterDefinition[name="GIT_REPOSITORY"]/defaultValue'
declare -r GIT_ARG='https://eos2git.cec.lab.emc.com/PIE/unity.git'
declare -r ACCUREV_ARG

# locate main script
declare -r UPDATE_JOBS="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. "${UPDATE_JOBS}/update_jobs" 