#!/bin/bash

declare -r PERFORM_UPDATE=${1:-'false'}
declare -r JOBS_DEFINITION_FILE='/emc/ballab1/Downloads/jenkins/jobs.txt'
declare -r XML_PATH='//hudson.plugins.emailext.ExtendedEmailPublisher/defaultSubject'
declare -r GIT_ARG='s/MRES/EMRS/'
declare -r ACCUREV_ARG='s/MRES/EMRS/'

# locate main script
declare -r UPDATE_JOBS="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. "${UPDATE_JOBS}/update_jobs"
