#!/bin/bash

declare -r PERFORM_UPDATE=${1:-'false'}
declare -r JOBS_DEFINITION_FILE
declare -r XML_PATH='//parameterDefinitions/hudson.model.StringParameterDefinition[name="ACCUREV_STREAM"]/defaultValue'
declare -r GIT_ARG
declare -r ACCUREV_ARG=upc-nextUnity-mcs

# locate main script
declare -r UPDATE_JOBS="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. "${UPDATE_JOBS}/update_jobs" 