#!/bin/bash

declare -r PERFORM_UPDATE=${1:-'false'}
declare -r JOBS_DEFINITION_FILE
declare -r XML_PATH='//publishers/org.jvnet.hudson.plugins.groovypostbuild.GroovyPostbuildRecorder/script/script'
declare -r GIT_ARG='/emc/ballab1/Downloads/jenkins/post.groovy'
declare -r ACCUREV_ARG='/emc/ballab1/Downloads/jenkins/post.groovy'

# locate main script
declare -r UPDATE_JOBS="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. "${UPDATE_JOBS}/update_jobs"
